### ISSUE TITLE
branch Scala 2.11 community build was using went away

### ISSUE THREAD

**Issue by SethTisue** [scalamacros/paradise#89] opened 2016-12-03 17:38 UTC
there used to be a 2.11.x branch that the community build was tracking. the commit we were using 1e7f980e5b63c3bc6b416ccceab71d6021f05d09, doesn't seem to be on any branch anymore. if I try to use your 2.11.8 branch, I get the compiler crash you see at https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-community-build/429/console

**Comment by xeno-by** [comment] 2016-12-03 22:58
I gave up on n.mm.x branches, because I'm having hard time to even keep up with stable releases, let alone unstable snapshots :) I'm sorry to hear this broke the community build.

How do I reproduce the crash? Which version of Scala should I use?

**Comment by xeno-by** [comment] 2016-12-03 23:36
Allright, can reproduce with https://github.com/scalamacros/paradise/commit/a83336ede12a16ccd92191cb195642e7471b52d2:

```
import scala.reflect.macros.whitebox.Context
import scala.language.experimental.macros
import scala.annotation.StaticAnnotation

object identityMacro {
  def impl(c: Context)(annottees: c.Expr[Any]*): c.Expr[Any] = {
    import c.universe._
    c.Expr[Any](Block(annottees.map(_.tree).toList, Literal(Constant(()))))
  }
}

class identity extends StaticAnnotation {
  def macroTransform(annottees: Any*): Any = macro identityMacro.impl
}
```

```
object M {
  @identity object X
  @identity class X()
}
```

**Comment by xeno-by** [comment] 2016-12-04 00:08
Looks like I erroneously merged https://github.com/scalamacros/paradise/pull/81, and that was crashing tests. I reverted the merge. Try again with the `2.11.9` branch.

**Closed as completed by xeno-by** 2016-12-04 00:08 UTC
